config/routes.rb
Demo::Application.routes.draw do

   root 'home#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :entries do
    resources :comments
  end  
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :home
  resources :relationships, only: [:create, :destroy]

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  include ApplicationHelper 
  has_many :comments, dependent: :destroy
  belongs_to :user

  after_destroy :a_destroy
  after_save :a_save

  	def a_destroy
      publish
  	end

  	def a_save
      publish
  	end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  def change
    create_table :relationships do |t|
      t.integer :follower_id
      t.integer :followed_id
      t.timestamps null: false
    end
    add_index :relationships, :follower_id
    add_index :relationships, :followed_id
    add_index :relationships, [:follower_id, :followed_id], unique: true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :entry, dependent: :destroy
	has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

  #@user.following
  #@user.followers
  
  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
    # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include CommentsHelper
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create	
    @entry = Entry.find(params[:entry_id])
    #We use the create method on @article.comments to create and save the comment.
    #This will automatically link the comment so that it belongs to that particular article.
    params[:comment][:user_id] = current_user.id
    @comment = @entry.comments.create(comment_params)
    redirect_to user_path(@entry.user_id)
  end

  def destroy
    @entry = Entry.find(params[:entry_id])
    @comment = @entry.comments.find(params[:id])
    @comment.destroy
    redirect_to user_path(@entry.user_id)
  end
 
  private
    def comment_params	
      params.require(:comment).permit(:body,:user_id)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @user = User.find(current_user)
    @entries = @user.entry
  end

  def new
  end

  def create
    user = User.find(current_user)
    entry = user.entry.create(entry_params)
    redirect_to user_path(current_user)
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
 
    if @entry.update_attributes entry_params
       #redirect_to @article
       #redirect_to articles_path
       flash[:success] = "Update success!"
       #redirect_to entries_url
       redirect_to user_path(current_user)
    else
     render 'edit'
    end

  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
 
    #redirect_to entries_path
    redirect_to user_path(current_user)
  end  
#=========================================================================================================================

  private
  def entry_params
    params.require(:entry).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if(current_user != nil)
      @users = current_user.following
        @feeds = Array.new()
        i = 0
        @users.each do |user|
          @entries = user.entry.order('updated_at DESC').limit(3)
            @entries.each do |e|
              @feeds[i] = e
              i = i+1
            end
        end
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    #logging in is handled by sending a POST request to the create action 

  	email = params[:session][:email].downcase
    pass = params[:session][:password];

    user = User.find_by(email: email)
    if user && pass==(user.password)
      log_in user
      redirect_to current_user
      #infer that /user(current_user) => call user#show
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    #logging out is handled by sending a DELETE request to the destroy action 
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
    	# Redirect to /user <=> call show action
    	# Just pass :id for /users (/users/:id)
      redirect_to @user 
    else
      render 'new'
    end
  end

   def show
  	@user = User.find(params[:id])
    @entries = @user.entry
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include EntriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def get_commentor(user_id)
    return User.find(user_id);
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def publish
	  data = {:from => "4", :to => "5", :sms =>""}
      $redis.publish :happy, data.to_json
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
  <div class="panel-body">
      <li>
    <div class="commenterImage">
      <img src="http://lorempixel.com/50/50/people/6" />
    </div>
    <div width="300px">
    <%user = get_commentor(comment.user_id)%>
      <%=link_to "Commentor:#{user.name}", user_path(user)%>
    </div>
    <hr>
    <div class="commentText">
        <p class="">
        <%= comment.body %>
        </p> 
        <span class="date sub-text">
          <%= comment.updated_at %>
        </span>
        <span>
          <%if (current_user != nil &&
               (current_user.id == comment.user_id ||
                current_user.id == comment.entry.user_id))
          %>
            <%= link_to 'Delete', [comment.entry, comment],
               method: :delete,
               data: { confirm: 'Are you sure?',
               :class=>"date sub-text" } %>
       
          <%end%> 
        </span>
    </div>
  </li>
</div>

app/views/comments/_form.html.erb
<%if (current_user != nil&&(
	current_user.following?(@entry.user)) ||
	 current_user.id == @entry.user.id)%>
  <%= form_for([@entry, @entry.comments.build]) do |f| %>
   <div class="form-group">
   <%= f.text_area :body, :class => "form-control", :placeholder=>"Your comments" %>
   </div>
   <div class="form-group">
     <%= f.submit "Comment", :class=>"btn btn-default" %>
   </div>
  <%end%>
<%end%>

app/views/entries/_new.html.erb
<!--
<%= link_to 'Back', entries_path %>

<%= form_for :entry, url: entries_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
-->
<h1></h1>
<div class="detailBox">
<%if current_user != nil%>
  <%= form_for :entry, url: entries_path do |f| %>
    <div class="form-group">
   <%= f.text_field :title ,:class=>"form-control",:placeholder=>"Title"%>
   </div>
   <div class="form-group">
   <%=f.text_area :body,:class=>"form-control", :placeholder=>"What is on your mind" %>
   </div>
   <div class="form-group">
     <%= f.submit "Post",:class=>"btn btn-default"%>
   </div>
  <%end%>
<%end%>
</div>

app/views/entries/edit.html.erb
<%= form_for @entry, method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, "value" => @entry.title%>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, :value => @entry.body%>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<%= link_to 'Home', home_index_path %>
<hr>
<%= link_to 'New Post', new_entry_path %>
<hr>
<table>
  <tr>
    <th>From</th>
    <th>Title</th>
    <th>Body</th>
    <th>Date</th>
    <th>Action</th>
  </tr>
 
  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.user_id %></td>
      <td><%= entry.title %></td>
      <td><%= entry.body %></td>
      <td><%= entry.updated_at %></td>
      <td><%= link_to 'Show', entry_path(entry) %></td>
      <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
      <td><%= link_to 'Destroy', entry_path(entry),
              method: :delete,
              data: { confirm: 'Drop this entry?' } %></td>
    </tr>
  <% end %>
</table>

app/views/entries/show.html.erb
 <h2>Entry detail</h2>
<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>
 
<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<hr>
<%= render @entry.comments %>

<%= render 'comments/form' %>

app/views/home/_index.html.erb
<div width="100%" class="bs-example bs-navbar-top-example" 
     data-example-id="navbar-fixed-to-top">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div width="100%" class="navbar-header">
          <%=link_to 'New feed', home_index_path,:class => "navbar-brand" %>
          <%= link_to 'Friend', users_path ,:class => "navbar-brand"%>
          <%= link_to 'Sign up', new_user_path ,:class => "navbar-brand"%>
          <%= link_to 'Sign out', logout_path, method: :delete,:class => "navbar-brand" %>
          <%if (current_user== nil) %>
          <%= link_to 'Sign in', login_path ,:class => "navbar-brand"%>
          <%else%>
          <%= link_to "Personal(#{current_user.name})", user_path(current_user),:class => "navbar-brand"%>
          <%end%>
        </div>
      </div>
    </nav>
  </div>

app/views/home/index.html.erb
<div class="detailBox">
<h1>New feeds</h1>
</div>
<%if current_user != nil%>
<script>
  var socket;
  socket = io.connect('http://localhost:1234');
  socket.on(<%=current_user.id%>, function(data) {
    location.reload();
  });
</script>
<% @feeds.each do |entry| %>
<div class="detailBox">
    <div class="titleBox">
      <label>
      <%=link_to "Postor:#{entry.user.name}" %> 
      Title: <%= entry.title %>
      </label>
      <button type="button" class="close" aria-hidden="true">&times;
      </button>
    </div>
    <div class="commentBox">
        <p class="taskDescription"><%= entry.body %></p>
        <p>
          <span class="date sub-text">on <%= entry.updated_at %></span>
        </p>
    </div>
    <div class="actionBox">
      <%
        @collapseOne = entry.id
      %>
      <a data-toggle="collapse" data-parent="#accordion" 
      href='<%='#'%><%=@collapseOne%>'
        aria-expanded="true" aria-controls="<%=@collapseOne%>" 
        class="collapsed">
        Comments
      </a>
        <ul class="commentList">
        <div class="bs-example" data-example-id="collapse-accordion">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div id="<%=@collapseOne%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
      <%= render entry.comments %>
      </div>
    </div>
  </div>
</div>
        
        </ul>
        <%@entry = entry%>
        <%= render 'comments/form' %>
    </div>
</div>
<% end %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

body { padding-top: 100px; }
<%=render 'home/index'%>
body { padding-top: 200px; }
<%= yield %>

</body>
</html>

app/views/users/_follow.html.erb
<p>
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div>
  <%= hidden_field_tag :followed_id, @user.id %>
  </div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>
</p>
<!--
former sends a POST request to the Relationships controller to create a relationship, while the latter sends a DELETE request to destroy a relationship
-->

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/users/_show_follow.html.erb
<H1></H1>

<span>
<%= link_to "Back to my home", user_path%>
</span>

<div class="detailBox">
<table class="table">
      <caption>Users</caption>
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%=user.id%></th>
          <td><%= link_to user.name, user_path(user)%></td>
          <td><%= user.email %></td>
        </tr>
       <% end %> 
      </tbody>
    </table>
</div>

app/views/users/_unfollow.html.erb
<p>
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow",class: "btn btn-primary" %>
<% end %>
</p>
<!--
former sends a POST request to the Relationships controller to create a relationship, while the latter sends a DELETE request to destroy a relationship
-->

app/views/users/followers.html.erb
<div class="detailBox">
<h1>followers</h1>
<%= render "show_follow"%>
</div>

app/views/users/following.html.erb
<div class="detailBox">
<h1>following</h1>
<%= render "show_follow"%>
</div>

app/views/users/index.html.erb
<div class="detailBox">
<h1>All User</h1>
<table class="table">
      <caption>Users</caption>
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Password</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%=user.id%></th>
          <td><%= link_to user.name, user_path(user)%></td>
          <td><%= user.email %></td>
          <td><%= user.password %></td>
        </tr>
       <% end %> 
      </tbody>
    </table>
</div>

app/views/users/new.html.erb
<div class="detailBox">
 <h1>Create New User</h1>   
<div class="bs-example" data-example-id="basic-forms">
    <%= form_for(@user) do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name,:class => "form-control",:placeholder => "Name" %>
    </div>
    <div class="form-group">
      <label>Email address</label>
      <%= f.email_field :email,:class => "form-control",:placeholder => "Enter email" %>
    </div>
    <div class="form-group">
      <label>Password</label>
      <%= f.password_field :password, :class=>"form-control",:placeholder=>"Password" %>
    </div>
    <div class="form-group">
        <label>Re-Password</label>
        <%= f.password_field :password_confirmation, :class=>"form-control",
        :placeholder=>"Re-Password" %>
      </div>
      

      <button type="submit" class="btn btn-default">Submit</button>
    <% end %>
  </div>
</div>  

app/views/users/show.html.erb
<div class="detailBox">
<H1>Well come to <%=@user.name%> 's home</H1>
  <%if(current_user!=nil && current_user.id != @user.id ) %>
    <%= render 'users/follow_form' %>
  <%end%>
  <%= link_to "Following(#{@user.following.count})",following_user_path(@user) %>
  <%= link_to "followers(#{@user.followers.count})",followers_user_path(@user) %>
</div>


<%if(current_user!=nil && current_user.id == @user.id) %>
  <%= render 'entries/new' %>
<%end%>

<% @entries.order('created_at DESC').each do |entry| %>
<div class="detailBox">
    <div class="titleBox">
      <label>
      <%=link_to "Postor:#{entry.user.name}" %> 
      Title: <%= entry.title %>
      </label>
      <button type="button" class="close" aria-hidden="true">&times;
      </button>
    </div>
    <div class="commentBox">
        <p class="taskDescription"><%= entry.body %></p>
        <p>
          <span class="date sub-text">on <%= entry.updated_at %></span>
        </p>
        <span class="taskDescription">
          <%#= link_to 'Show', entry_path(entry) %>
        </span>
        <%if(current_user!=nil && current_user.id == @user.id )%>
        <span class="taskDescription">
        <%= link_to 'Edit', edit_entry_path(entry) %>
        </span>
        <span class="taskDescription">
          <%= link_to 'Destroy', entry_path(entry),
              method: :delete,
              data: { confirm: 'Drop this entry?' } %>
        </span>
        <%end%>
    </div>
    <div class="actionBox">
      <%
        @collapseOne = entry.id
      %>
      <a data-toggle="collapse" data-parent="#accordion" 
      href='<%='#'%><%=@collapseOne%>'
        aria-expanded="true" aria-controls="<%=@collapseOne%>" 
        class="collapsed">
        Comments
      </a>
        <ul class="commentList">
        <div class="bs-example" data-example-id="collapse-accordion">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div id="<%=@collapseOne%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
      <%= render entry.comments %>
      </div>
    </div>
  </div>
</div>
        
        </ul>
        <%@entry = entry%>
        <%= render 'comments/form' %>
    </div>
</div>
<%end%>